language: csharp
before_install:
  - sudo apt-get install nunit-console
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number
install:
  - mono .nuget/nuget.exe restore TaskCat/TaskCat.sln -Verbosity detailed
script:
  - xbuild /p:Configuration=Release TaskCat/TaskCat.sln
after_script:
  - nunit-console TaskCat/TaskCat.Tests/bin/Release/TaskCat.Tests.dll
